<?php
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;


/**
 * Generated by Database Modeler Lite
 * https://play.google.com/store/apps/details?id=adrian.adbm
 * 
 * Created: Jul 24, 2021
*/

class CreateCountriesTable extends Migration {

    public function up() {
        Schema::create('countries', function (Blueprint $table) {
            $table->increments('id');
            $table->string('cc', 3)->nullable;
            $table->string('name', 100)->nullable();
            $table->string('language', 100)->nullable();
            $table->string('flag', 100)->nullable();
            $table->string('notes', 100)->nullable();
            $table->string('external_img', 100)->nullable();
			$table->timestamps();
			$table->softDeletes();
        });
    }

    public function down() {
        Schema::dropIfExists('countries');
    }
}
