<?php
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;


/**
 * Generated by Database Modeler Lite
 * https://play.google.com/store/apps/details?id=adrian.adbm
 * 
 * Created: Jul 24, 2021
*/

class CreateComponentEntriesTable extends Migration {

    public function up() {
        Schema::create('component_entries', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('country_id')->nullable()->unsigned();
            $table->string('content', 2000)->nullable();
            $table->integer('component_id')->nullable()->unsigned();
            $table->foreign('country_id')->references('id')->on('countries');
            $table->foreign('component_id')->references('id')->on('components');
			$table->timestamps();
			$table->softDeletes();
        });
    }

    public function down() {
        Schema::table('countries', function (Blueprint $table) {
            $table->dropForeign(['country_id']);
        });
        Schema::table('components', function (Blueprint $table) {
            $table->dropForeign(['component_id']);
        });
        Schema::dropIfExists('component_entries');
    }
}
