<?php
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;


/**
 * Generated by Database Modeler Lite
 * https://play.google.com/store/apps/details?id=adrian.adbm
 * 
 * Created: Jul 24, 2021
*/

class CreatePurchasingFunctionsTable extends Migration {

    public function up() {
        Schema::create('purchasing_functions', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('country_id')->nullable()->unsigned();
            $table->string('column', 100)->nullable();
            $table->string('financial_mgmt', 100)->nullable();
            $table->string('benefits_spec', 100)->nullable();
            $table->string('contracting', 100)->nullable();
            $table->string('provider_payment', 100)->nullable();
            $table->string('monitoring', 100)->nullable();
            $table->string('notes', 100)->nullable();
            $table->foreign('country_id')->references('id')->on('countries');
			$table->timestamps();
			$table->softDeletes();
        });
    }

    public function down() {
        Schema::table('countries', function (Blueprint $table) {
            $table->dropForeign(['country_id']);
        });
        Schema::dropIfExists('purchasing_functions');
    }
}
