<?php
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;


/**
 * Generated by Database Modeler Lite
 * https://play.google.com/store/apps/details?id=adrian.adbm
 * 
 * Created: Jul 24, 2021
*/

class CreateContextsTable extends Migration {

    public function up() {
        Schema::create('contexts', function (Blueprint $table) {
            $table->increments('id');
            $table->string('slug', 100)->nullable();
            $table->string('english', 100)->nullable();
            $table->string('french', 100)->nullable();
			$table->timestamps();
			$table->softDeletes();
        });
    }

    public function down() {
        Schema::dropIfExists('contexts');
    }
}
