<?php
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;


/**
 * Generated by Database Modeler Lite
 * https://play.google.com/store/apps/details?id=adrian.adbm
 * 
 * Created: Jul 24, 2021
*/

class CreateCountrySponsorTable extends Migration {

    public function up() {
        Schema::create('country_sponsor', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('country_id')->nullable()->unsigned();
            $table->integer('sponsor_id')->nullable()->unsigned();
            $table->foreign('country_id')->references('id')->on('countries');
            $table->foreign('sponsor_id')->references('id')->on('sponsors');
			$table->timestamps();
			$table->softDeletes();
        });
    }

    public function down() {
        Schema::table('countries', function (Blueprint $table) {
            $table->dropForeign(['country_id']);
        });
        Schema::table('sponsors', function (Blueprint $table) {
            $table->dropForeign(['sponsor_id']);
        });
        Schema::dropIfExists('country_sponsor');
    }
}
